using CcDashboard.Application.Interfaces;
using CcDashboard.Contracts.DTOs.Dashboards;
using CcDashboard.Domain.Domain;
using CcDashboard.Domain.Exceptions;
using CcDashboard.Domain.Interfaces;
using MediatR;

namespace CcDashboard.Application.Commands.Dashboards;

public record SaveDashboardWidgetCommand(
    Guid DashboardId,
    DashboardWidgetDto Widget) : IRequest<int>
{
    // Returns the GridId (auto-generated for new widgets)
}

public class SaveDashboardWidgetCommandHandler(
    IDashboardRepository dashboards,
    IUnitOfWork unitOfWork,
    ICurrentUserAccessor currentUser,
    IDateTimeProvider clock)
    : IRequestHandler<SaveDashboardWidgetCommand, int>
{
    public async Task<int> Handle(SaveDashboardWidgetCommand cmd, CancellationToken ct)
    {
        var isSuperadmin = currentUser.Role == "Superadmin";
        var dashboard = await dashboards.GetByIdWithWidgetsAsync(cmd.DashboardId, bypassTenantFilter: isSuperadmin, ct)
            ?? throw new NotFoundException(nameof(Dashboard), cmd.DashboardId);

        var tenantId = dashboard.TenantId;
        var dto = cmd.Widget;

        var existing = dashboard.Widgets.FirstOrDefault(w => w.Id == dto.Id);
        if (existing != null)
        {
            // Update existing widget
            existing.WidgetCatalogItemId = dto.WidgetCatalogItemId;
            existing.PositionJson = dto.PositionJson;
            existing.ConfigJson = dto.ConfigJson;

            dashboard.UpdatedAt = clock.UtcNow;
            dashboard.UpdatedByUserId = currentUser.UserId!.Value;
            dashboards.Update(dashboard);

            await unitOfWork.SaveChangesAsync(ct);
            return existing.GridId;
        }
        else
        {
            // Create new widget - GridId will be auto-generated by database
            var newWidget = new DashboardWidget
            {
                Id = dto.Id,
                DashboardId = dashboard.Id,
                TenantId = tenantId,
                WidgetCatalogItemId = dto.WidgetCatalogItemId,
                PositionJson = dto.PositionJson,
                ConfigJson = dto.ConfigJson,
                IsDeleted = false
            };

            dashboard.Widgets.Add(newWidget);
            dashboard.UpdatedAt = clock.UtcNow;
            dashboard.UpdatedByUserId = currentUser.UserId!.Value;
            dashboards.Update(dashboard);

            // SaveChanges populates GridId from database identity
            await unitOfWork.SaveChangesAsync(ct);

            return newWidget.GridId;
        }
    }
}
