// <auto-generated />
using System;
using CcDashboard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CcDashboard.Infrastructure.Migrations.BackendEmulation
{
    [DbContext(typeof(BackendEmulationDbContext))]
    [Migration("20260526203609_AddRtsDataEntitiesAndStatusGroup")]
    partial class AddRtsDataEntitiesAndStatusGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcAgentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NGC_AgentGroups", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcBusinessUnit", b =>
                {
                    b.Property<int>("BusinessUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("BusinessUnitId"));

                    b.Property<string>("BusinessUnitName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("SiteId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("BusinessUnitId");

                    b.HasIndex("SiteId");

                    b.ToTable("NGC_BusinessUnit", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcBusinessUnitQueueClassification", b =>
                {
                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("QueueId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClassificationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("BusinessUnitId", "QueueId");

                    b.ToTable("NGC_BusinessUnitQueueClassification", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcBusinessUnitSupergroup", b =>
                {
                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<int>("SupergroupId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("BusinessUnitId", "SupergroupId");

                    b.HasIndex("SupergroupId");

                    b.ToTable("NGC_BusinessUnitSupergroup", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NGC_Queues", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcSite", b =>
                {
                    b.Property<string>("SiteId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClearTime")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SiteName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("SiteId");

                    b.ToTable("NGC_Site", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcSupergroup", b =>
                {
                    b.Property<int>("SupergroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("SupergroupId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("SupergroupIdOld")
                        .HasColumnType("integer");

                    b.Property<string>("SupergroupName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("SupergroupId");

                    b.ToTable("NGC_Supergroup", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcSupergroupAgentgroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentgroupId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SupergroupId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SupergroupId");

                    b.ToTable("NGC_SupergroupAgentgroup", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.RtsDataInteraction", b =>
                {
                    b.Property<string>("InteractionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Segment")
                        .HasColumnType("integer");

                    b.Property<string>("OnDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ServerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Workgroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("AnsweredDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CallType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClassificationCode")
                        .HasColumnType("text");

                    b.Property<string>("CustomCallData")
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("InQueueDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InteractionType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsAbandoned")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsAnswered")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsCallbackRequest")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsInQueue")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsMessaging")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsTalk")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsTransferred")
                        .HasColumnType("boolean");

                    b.Property<string>("LastUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastWorkgroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RemoteAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TalkTime")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TimeInQueue")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("InteractionId", "Segment", "OnDate", "ServerId", "Workgroup");

                    b.ToTable("RTSData_Interaction", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.RtsDataUserStatus", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StatusId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ServerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OnDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MaxDuration")
                        .HasColumnType("integer");

                    b.Property<string>("StatusGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StatusName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalDuration")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "StatusId", "ServerId", "OnDate");

                    b.ToTable("RTSData_UserStatus", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.RtsDataUserStatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ServerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusGroup")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatusId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("RTSData_UserStatusLog", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.RtsGridCell", b =>
                {
                    b.Property<int>("CellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("CellId"));

                    b.Property<string>("CellType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ColNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ColumnId")
                        .HasColumnType("integer");

                    b.Property<int?>("NewRowId")
                        .HasColumnType("integer");

                    b.Property<int?>("OldRowId")
                        .HasColumnType("integer");

                    b.Property<string>("OnClick")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RowId")
                        .HasColumnType("integer");

                    b.Property<int?>("StyleId")
                        .HasColumnType("integer");

                    b.Property<int?>("ThresholdSetId")
                        .HasColumnType("integer");

                    b.Property<string>("Tooltip")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("UnionId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("CellId");

                    b.ToTable("RTSGrid_Cell", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.RtsGridColumn", b =>
                {
                    b.Property<int>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ColumnId"));

                    b.Property<int?>("CellTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("integer");

                    b.Property<int>("GridId")
                        .HasColumnType("integer");

                    b.HasKey("ColumnId");

                    b.ToTable("RTSGrid_Column", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.RtsGridGrid", b =>
                {
                    b.Property<int>("GridId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("GridId"));

                    b.Property<int?>("StyleId")
                        .HasColumnType("integer");

                    b.Property<string>("ThresholdScript")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UnionId")
                        .HasColumnType("integer");

                    b.HasKey("GridId");

                    b.ToTable("RTSGrid_Grid", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.RtsGridMetric", b =>
                {
                    b.Property<string>("MetricId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MetricFormat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetricFunction")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MetricParameter")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Agent");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("String");

                    b.HasKey("MetricId");

                    b.ToTable("RTSGrid_Metric", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.RtsGridRow", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("RowId"));

                    b.Property<int>("GridId")
                        .HasColumnType("integer");

                    b.Property<int?>("OldRowId")
                        .HasColumnType("integer");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("StyleId")
                        .HasColumnType("integer");

                    b.Property<string>("ThresholdScript")
                        .HasColumnType("text");

                    b.Property<int?>("UnionId")
                        .HasColumnType("integer");

                    b.HasKey("RowId");

                    b.ToTable("RTSGrid_Row", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.RtsUserGridColumn", b =>
                {
                    b.Property<int>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ColumnId"));

                    b.Property<int>("ColumnsOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ColumnsSetId")
                        .HasColumnType("integer");

                    b.Property<string>("MetricId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("StyleId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ColumnId");

                    b.ToTable("RTSUserGrid_Column", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.RtsUserGridColumnsSet", b =>
                {
                    b.Property<int>("ColumnsSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ColumnsSetId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ColumnsSetId");

                    b.ToTable("RTSUserGrid_ColumnsSet", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.RtsUserGridGrid", b =>
                {
                    b.Property<int>("GridId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("GridId"));

                    b.Property<bool?>("AllowPaging")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AllowScroll")
                        .HasColumnType("boolean");

                    b.Property<int?>("ColumnsSetId")
                        .HasColumnType("integer");

                    b.Property<string>("NoRecordsText")
                        .HasColumnType("text");

                    b.Property<int?>("PageSize")
                        .HasColumnType("integer");

                    b.Property<string>("RowsFilter")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RowsFilterNew")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("StyleId")
                        .HasColumnType("integer");

                    b.Property<string>("TextDirection")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("ThresholdScript")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UnionId")
                        .HasColumnType("integer");

                    b.HasKey("GridId");

                    b.ToTable("RTSUserGrid_Grid", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcBusinessUnit", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.NgcSite", "Site")
                        .WithMany("BusinessUnits")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcBusinessUnitQueueClassification", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.NgcBusinessUnit", "BusinessUnit")
                        .WithMany("QueueAssignments")
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessUnit");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcBusinessUnitSupergroup", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.NgcBusinessUnit", "BusinessUnit")
                        .WithMany("SupergroupAssignments")
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcDashboard.Domain.Domain.NgcSupergroup", "Supergroup")
                        .WithMany("BusinessUnitAssignments")
                        .HasForeignKey("SupergroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessUnit");

                    b.Navigation("Supergroup");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcSupergroupAgentgroup", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.NgcSupergroup", "Supergroup")
                        .WithMany("AgentGroupAssignments")
                        .HasForeignKey("SupergroupId");

                    b.Navigation("Supergroup");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcBusinessUnit", b =>
                {
                    b.Navigation("QueueAssignments");

                    b.Navigation("SupergroupAssignments");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcSite", b =>
                {
                    b.Navigation("BusinessUnits");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.NgcSupergroup", b =>
                {
                    b.Navigation("AgentGroupAssignments");

                    b.Navigation("BusinessUnitAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
