// <auto-generated />
using System;
using CcDashboard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CcDashboard.Infrastructure.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712223405_DropAppOwnedBackendTables")]
    partial class DropAppOwnedBackendTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CcDashboard.Domain.Domain.AgentState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentStateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("AgentState");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AgentStateName")
                        .IsUnique();

                    b.ToTable("tenant_agent_states", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.AgentStateDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentStateGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentStateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentStateGroupId");

                    b.HasIndex("AgentStateId")
                        .IsUnique();

                    b.HasIndex("TenantId", "AgentStateId")
                        .IsUnique();

                    b.ToTable("tenant_agent_state_definitions", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.AgentStateGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "GroupName")
                        .IsUnique();

                    b.ToTable("tenant_agent_state_groups", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDarkMode")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("dashboards", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.DashboardCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("dashboard_categories", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.DashboardPermission", b =>
                {
                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionGroupId", "DashboardId");

                    b.HasIndex("DashboardId");

                    b.ToTable("dashboard_permissions", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.DashboardWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid");

                    b.Property<int>("GridId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GridId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PositionJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WidgetCatalogItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.HasIndex("WidgetCatalogItemId");

                    b.ToTable("dashboard_widgets", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Historical.HistAgentInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IntervalStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AgentDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AgentExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Handled")
                        .HasColumnType("integer");

                    b.Property<long>("SumAvailableMs")
                        .HasColumnType("bigint");

                    b.Property<long>("SumBreakMs")
                        .HasColumnType("bigint");

                    b.Property<long>("SumHoldMs")
                        .HasColumnType("bigint");

                    b.Property<long>("SumLoggedInMs")
                        .HasColumnType("bigint");

                    b.Property<long>("SumOnphoneMs")
                        .HasColumnType("bigint");

                    b.Property<long>("SumPaperworkMs")
                        .HasColumnType("bigint");

                    b.Property<long>("SumTrainingMs")
                        .HasColumnType("bigint");

                    b.Property<long>("SumUnavailableMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id", "IntervalStart");

                    b.ToTable("hist_agent_intervals", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Historical.HistAggregationWatermark", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AggregatedThrough")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId");

                    b.ToTable("hist_aggregation_watermarks", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Historical.HistQueueInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IntervalStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Abandoned")
                        .HasColumnType("integer");

                    b.Property<int>("Answered")
                        .HasColumnType("integer");

                    b.Property<int>("AnsweredInSl")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Offered")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QueueId")
                        .HasColumnType("uuid");

                    b.Property<long>("SumTalk")
                        .HasColumnType("bigint");

                    b.Property<long>("SumWaitAnswered")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Workgroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id", "IntervalStart");

                    b.ToTable("hist_queue_intervals", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Historical.UserReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("user_reports", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.HistoryMetric", b =>
                {
                    b.Property<string>("MetricId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MetricFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MetricFunction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MetricParameter")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MetricId");

                    b.ToTable("history_metrics", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.InfoSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SecondsPerMessage")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("info_slots", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.InfoSlotMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeactivatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InfoSlotId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("InfoSlotId", "IsActive", "ExpiresAt");

                    b.ToTable("info_slot_messages", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.InfoSlotPermission", b =>
                {
                    b.Property<Guid>("InfoSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("InfoSlotId", "PermissionGroupId");

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("info_slot_permissions", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.MenuPermission", b =>
                {
                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("MenuKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionGroupId", "MenuKey");

                    b.ToTable("menu_permissions", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("permission_groups", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.PgBusinessUnit", b =>
                {
                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionGroupId", "BusinessUnitId");

                    b.ToTable("pg_business_units", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.PgQueue", b =>
                {
                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionGroupId", "ObjectId");

                    b.ToTable("pg_queues", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.PgSkill", b =>
                {
                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionGroupId", "ObjectId");

                    b.ToTable("pg_skills", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.PgSupergroup", b =>
                {
                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("SupergroupId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionGroupId", "SupergroupId");

                    b.ToTable("pg_supergroups", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Reports.ReportCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("report_categories", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Reports.ReportPermission", b =>
                {
                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReportScreenId")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionGroupId", "ReportScreenId");

                    b.HasIndex("ReportScreenId");

                    b.ToTable("report_permissions", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Reports.ReportSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DateWindow")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FixedFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FixedTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Recipients")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ReportScreenId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RollingDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportScreenId");

                    b.HasIndex("TenantId", "IsActive", "NextRunAt");

                    b.ToTable("report_schedules", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Reports.ReportScreen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDarkMode")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("report_screens", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Reports.ReportWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PositionJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ReportScreenId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("WidgetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ReportScreenId");

                    b.HasIndex("TenantId");

                    b.ToTable("report_widgets", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.SsoConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimMappings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataUrl")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("sso_configurations", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.TenantSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("AuditRetentionDays")
                        .HasColumnType("integer");

                    b.Property<string>("BackgroundColorPalette")
                        .HasColumnType("text");

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailProviderConfig")
                        .HasColumnType("text");

                    b.Property<string>("FontColorPalette")
                        .HasColumnType("text");

                    b.Property<string>("FontSizes")
                        .HasColumnType("text");

                    b.Property<int>("MaxConcurrentConnections")
                        .HasColumnType("integer");

                    b.Property<int>("PasswordExpireDays")
                        .HasColumnType("integer");

                    b.Property<int>("PasswordMinLength")
                        .HasColumnType("integer");

                    b.Property<int>("PurchasedLicences")
                        .HasColumnType("integer");

                    b.Property<bool>("Require2faForAll")
                        .HasColumnType("boolean");

                    b.Property<string>("SignalRConnectionUrl")
                        .HasColumnType("text");

                    b.Property<int?>("SlThresholdSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("SoftDeleteDashboards")
                        .HasColumnType("boolean");

                    b.Property<int>("SoftDeleteRetentionDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SsoConfigurationId")
                        .HasColumnType("uuid");

                    b.HasKey("TenantId");

                    b.ToTable("tenant_settings", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRevoked", "ExpiresAt");

                    b.ToTable("user_sessions", "identity");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.UserWidgetSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WidgetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId", "WidgetId")
                        .IsUnique();

                    b.ToTable("user_widget_settings", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.WidgetCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("widget_catalog", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.WidgetTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WidgetCatalogItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WidgetCatalogItemId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("widget_templates", (string)null);
                });

            modelBuilder.Entity("CcDashboard.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("CcDashboard.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Is2faEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MustChangePasswordAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<Guid?>("PermissionGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredLocale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en-US");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("NormalizedEmail", "TenantId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("CcDashboard.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Jti")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("CcDashboard.Infrastructure.Identity.TwoFactorCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("two_factor_codes", "identity");
                });

            modelBuilder.Entity("CcDashboard.Infrastructure.Identity.UserPasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("user_password_history", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.AgentState", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.AgentStateDefinition", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.AgentStateGroup", "Group")
                        .WithMany("Definitions")
                        .HasForeignKey("AgentStateGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcDashboard.Domain.Domain.AgentState", "State")
                        .WithOne("Definition")
                        .HasForeignKey("CcDashboard.Domain.Domain.AgentStateDefinition", "AgentStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("State");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.AgentStateGroup", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Dashboard", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.DashboardCategory", "Category")
                        .WithMany("Dashboards")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CcDashboard.Domain.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.DashboardCategory", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.DashboardPermission", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.Dashboard", "Dashboard")
                        .WithMany("Permissions")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcDashboard.Domain.Domain.PermissionGroup", "PermissionGroup")
                        .WithMany("DashboardPermissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dashboard");

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.DashboardWidget", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.Dashboard", "Dashboard")
                        .WithMany("Widgets")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcDashboard.Domain.Domain.WidgetCatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("WidgetCatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("Dashboard");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.InfoSlotMessage", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.InfoSlot", "InfoSlot")
                        .WithMany("Messages")
                        .HasForeignKey("InfoSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfoSlot");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.InfoSlotPermission", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.InfoSlot", "InfoSlot")
                        .WithMany("Permissions")
                        .HasForeignKey("InfoSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcDashboard.Domain.Domain.PermissionGroup", "PermissionGroup")
                        .WithMany()
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfoSlot");

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.MenuPermission", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.PermissionGroup", "PermissionGroup")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.PermissionGroup", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.PgBusinessUnit", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.PermissionGroup", null)
                        .WithMany("AllowedBusinessUnits")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.PgQueue", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.PermissionGroup", null)
                        .WithMany("AllowedQueues")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.PgSkill", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.PermissionGroup", null)
                        .WithMany("AllowedSkills")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.PgSupergroup", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.PermissionGroup", null)
                        .WithMany("AllowedSupergroups")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Reports.ReportPermission", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.PermissionGroup", "PermissionGroup")
                        .WithMany()
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcDashboard.Domain.Domain.Reports.ReportScreen", "ReportScreen")
                        .WithMany("Permissions")
                        .HasForeignKey("ReportScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionGroup");

                    b.Navigation("ReportScreen");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Reports.ReportSchedule", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.Reports.ReportScreen", "ReportScreen")
                        .WithMany("Schedules")
                        .HasForeignKey("ReportScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportScreen");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Reports.ReportScreen", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.Reports.ReportCategory", "Category")
                        .WithMany("ReportScreens")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Reports.ReportWidget", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.Reports.ReportScreen", "ReportScreen")
                        .WithMany("Widgets")
                        .HasForeignKey("ReportScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportScreen");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.SsoConfiguration", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.Tenant", "Tenant")
                        .WithMany("SsoConfigurations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.TenantSettings", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.Tenant", "Tenant")
                        .WithOne("Settings")
                        .HasForeignKey("CcDashboard.Domain.Domain.TenantSettings", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.WidgetTemplate", b =>
                {
                    b.HasOne("CcDashboard.Domain.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcDashboard.Domain.Domain.WidgetCatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("WidgetCatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CcDashboard.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CcDashboard.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CcDashboard.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CcDashboard.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CcDashboard.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CcDashboard.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.AgentState", b =>
                {
                    b.Navigation("Definition");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.AgentStateGroup", b =>
                {
                    b.Navigation("Definitions");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Dashboard", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.DashboardCategory", b =>
                {
                    b.Navigation("Dashboards");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.InfoSlot", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.PermissionGroup", b =>
                {
                    b.Navigation("AllowedBusinessUnits");

                    b.Navigation("AllowedQueues");

                    b.Navigation("AllowedSkills");

                    b.Navigation("AllowedSupergroups");

                    b.Navigation("DashboardPermissions");

                    b.Navigation("MenuPermissions");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Reports.ReportCategory", b =>
                {
                    b.Navigation("ReportScreens");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Reports.ReportScreen", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Schedules");

                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("CcDashboard.Domain.Domain.Tenant", b =>
                {
                    b.Navigation("Settings");

                    b.Navigation("SsoConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
