#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate idempotent SQL backfill for RTSGrid_MetricTranslation from
docs/metrics-catalog.<locale>.json files. Source of truth = the JSON files.
Usage: python3 tools/gen_translation_backfill.py [--out db/data/05_metric_translations.sql]
"""
import json, argparse, os, sys

LOCALES = ["ru-RU", "he-IL"]
FIELDS = [("displayName","DisplayName"),("shortDescription","ShortDescription"),
          ("longDescription","LongDescription"),("comparison","Comparison")]

def sqlstr(v):
    if v is None: return "NULL"
    v = str(v).strip()
    if v == "": return "NULL"
    return "'" + v.replace("'", "''") + "'"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog-dir", default="docs")
    ap.add_argument("--out", default="-")
    a = ap.parse_args()
    rows = []
    for loc in LOCALES:
        path = os.path.join(a.catalog_dir, f"metrics-catalog.{loc}.json")
        d = json.load(open(path, encoding="utf-8"))
        for m in d["metrics"]:
            vals = [sqlstr(m['metricId']), f"'{loc}'"] + [sqlstr(m.get(jf)) for jf,_ in FIELDS]
            rows.append("    (" + ", ".join(vals) + ")")
    cols = '"MetricId", "Locale", ' + ", ".join(f'"{c}"' for _,c in FIELDS)
    sql = []
    sql.append("-- 05_metric_translations.sql — ru-RU + he-IL catalogue translations")
    sql.append("-- Generated by tools/gen_translation_backfill.py from docs/metrics-catalog.<locale>.json")
    sql.append("-- Idempotent: clears the two locales then re-inserts. Empty/null fields -> NULL (EN fallback in query).")
    sql.append("")
    sql.append("DELETE FROM \"RTSGrid_MetricTranslation\" WHERE \"Locale\" IN ('ru-RU','he-IL');")
    sql.append("")
    sql.append(f'INSERT INTO "RTSGrid_MetricTranslation" ({cols}) VALUES')
    sql.append(",\n".join(rows) + ";")
    out = "\n".join(sql) + "\n"
    if a.out == "-":
        sys.stdout.write(out)
    else:
        with open(a.out, "w", encoding="utf-8") as f:
            f.write(out); f.flush(); os.fsync(f.fileno())
        print(f"wrote {a.out}: {len(rows)} rows ({len(LOCALES)} locales x {len(rows)//len(LOCALES)})")

if __name__ == "__main__":
    main()
