namespace CcDashboard.Contracts.DTOs.TenantSettings;

public record TenantSettingsDto(
    Guid TenantId,
    int PasswordMinLength,
    int PasswordExpireDays,
    bool Require2faForAll,
    int AuditRetentionDays,
    string DefaultLocale,
    bool SoftDeleteDashboards,
    int SoftDeleteRetentionDays,
    int PurchasedLicences,
    int MaxConcurrentConnections,
    string? SignalRConnectionUrl,
    List<string>? BackgroundColorPalette,
    List<string>? FontColorPalette,
    List<string>? FontSizes,
    // WFM Phase 1 config (spec §5)
    List<string>? WfmServingStateGroups,
    int WfmWindowMinutes,
    double WfmSlTargetPct,
    int WfmSlThresholdSec,
    int WfmTrunkCapacity,
    double WfmDefaultShrinkage,
    bool WfmEnableRealtime,
    string? WfmThresholds);

public record UpdateTenantSettingsRequest(
    int PasswordMinLength,
    int PasswordExpireDays,
    bool Require2faForAll,
    int AuditRetentionDays,
    string DefaultLocale,
    bool SoftDeleteDashboards,
    int SoftDeleteRetentionDays,
    int PurchasedLicences,
    int MaxConcurrentConnections,
    string? SignalRConnectionUrl,
    List<string>? BackgroundColorPalette,
    List<string>? FontColorPalette,
    List<string>? FontSizes,
    // WFM Phase 1 config (spec §5)
    List<string>? WfmServingStateGroups,
    int WfmWindowMinutes,
    double WfmSlTargetPct,
    int WfmSlThresholdSec,
    int WfmTrunkCapacity,
    double WfmDefaultShrinkage,
    bool WfmEnableRealtime,
    string? WfmThresholds);
